Support multiple NXP platforms - i.MX6Q - i.MX6ULL - i.MX8MP - i.MX93 QSB - Layerscape ls1028ardb
And some other changes
- Fix Orangepi 5 building issue
- Fix StarFive VisionFive 2 building issue
- Rename files

Signed-off-by: Aristo Chen <aristo.chen@canonical.com>

diff --git a/kernel_snap/snap/snapcraft.yaml b/kernel_snap/snap/snapcraft.yaml
--- a/kernel_snap/snap/snapcraft.yaml
+++ b/kernel_snap/snap/snapcraft.yaml
@@ -123,6 +123,10 @@ parts:
     override-build: |
       cp "${CRAFT_PROJECT_DIR}"/its/kernel.its ./
       ITS_FDT_PATH=$(find "${CRAFT_STAGE}" -name "__ITS_FDT_NAME__" | sed 's/.*stage\/\(.*dtb\)/\1/')
+      if [ -z "${ITS_FDT_PATH}" ];then
+        echo "Failed to find dtb file called ${ITS_FDT_PATH}"
+        exit 1
+      fi
 
       d=$'\x03'
       sed -i "s${d}__ITS_FDT_PATH__${d}${ITS_FDT_PATH}${d}g" kernel.its
